from typing import List, Dict, Optional
from app.models.area import ProtectedAreaModel, AreaStatisticsModel, AreaTimelineModel
from app.models.hotspot import HotspotModel, HotspotRelatedAlert
from app.models.alert import AlertModel
from app.models.report import ReportModel


class InMemoryDatabase:
    """In-memory geospatial database seeded with global and Indian protected reserve records."""

    def __init__(self):
        self.areas: Dict[str, ProtectedAreaModel] = {}
        self.hotspots: Dict[str, HotspotModel] = {}
        self.alerts: Dict[str, AlertModel] = {}
        self.reports: Dict[str, ReportModel] = {}
        self.timelines: Dict[str, List[AreaTimelineModel]] = {}
        self.statistics: Dict[str, AreaStatisticsModel] = {}

        self._seed_data()

    def _seed_data(self):
        # 1. Seed Protected Areas
        areas_data = [
            ProtectedAreaModel(
                id="area-kanha",
                wdpa_id="WDPA-892",
                name="Kanha National Park",
                designation="Tiger Reserve & National Park",
                protected_area_type="National Park & Tiger Reserve",
                iucn_category="II",
                country="India",
                country_code="IN",
                state="Madhya Pradesh",
                area_km2=940.0,
                total_hectares=94000.0,
                coordinates={"lat": 22.3345, "lon": 80.6115},
                forest_cover_percent=78.4,
                canopy_loss_year_ha=31.2,
                active_fires_count=3,
                threat_index=34,
                biome="Central Deccan Moist Deciduous & Sal Woodlands",
                last_analyzed="2026-09-18T03:30:00Z",
            ),
            ProtectedAreaModel(
                id="area-bandhavgarh",
                wdpa_id="WDPA-896",
                name="Bandhavgarh National Park",
                designation="Tiger Reserve",
                protected_area_type="National Park & Tiger Reserve",
                iucn_category="II",
                country="India",
                country_code="IN",
                state="Madhya Pradesh",
                area_km2=1536.0,
                total_hectares=153600.0,
                coordinates={"lat": 23.7042, "lon": 80.9995},
                forest_cover_percent=71.9,
                canopy_loss_year_ha=42.6,
                active_fires_count=5,
                threat_index=48,
                biome="Vindhyan Dry Deciduous & Bamboo Mixed Forest",
                last_analyzed="2026-09-18T02:45:00Z",
            ),
            ProtectedAreaModel(
                id="area-satpura",
                wdpa_id="WDPA-901",
                name="Satpura Tiger Reserve",
                designation="Tiger Reserve & Biosphere",
                protected_area_type="Tiger Reserve & Biosphere Reserve",
                iucn_category="II",
                country="India",
                country_code="IN",
                state="Madhya Pradesh",
                area_km2=2133.0,
                total_hectares=213300.0,
                coordinates={"lat": 22.4833, "lon": 78.2333},
                forest_cover_percent=81.2,
                canopy_loss_year_ha=38.9,
                active_fires_count=4,
                threat_index=39,
                biome="Satpura Range Montane Deciduous & Teak Forests",
                last_analyzed="2026-09-18T04:10:00Z",
            ),
            ProtectedAreaModel(
                id="area-2",
                wdpa_id="WDPA-1240",
                name="Kaziranga National Park",
                designation="Tiger Reserve & World Heritage",
                protected_area_type="National Park & Tiger Reserve",
                iucn_category="II",
                country="India",
                country_code="IN",
                state="Assam",
                area_km2=858.0,
                total_hectares=85800.0,
                coordinates={"lat": 26.5775, "lon": 93.1711},
                forest_cover_percent=68.5,
                canopy_loss_year_ha=49.3,
                active_fires_count=1,
                threat_index=45,
                biome="Brahmaputra Valley Semi-Evergreen & Floodplain",
                last_analyzed="2026-09-18T01:15:00Z",
            ),
            ProtectedAreaModel(
                id="area-1",
                wdpa_id="WDPA-755",
                name="Serengeti National Park",
                designation="National Park & World Heritage",
                protected_area_type="National Park (IUCN Category II)",
                iucn_category="II",
                country="Tanzania",
                country_code="TZ",
                state="Mara & Simiyu Regions",
                area_km2=14763.0,
                total_hectares=1476300.0,
                coordinates={"lat": -2.3333, "lon": 34.8333},
                forest_cover_percent=74.2,
                canopy_loss_year_ha=142.8,
                active_fires_count=6,
                threat_index=38,
                biome="Tropical & Subtropical Grasslands, Savannas",
                last_analyzed="2026-09-17T18:30:00Z",
            ),
            ProtectedAreaModel(
                id="area-3",
                wdpa_id="WDPA-3294",
                name="Yasuní National Park",
                designation="Biosphere Reserve",
                protected_area_type="National Park & UNESCO Biosphere Reserve",
                iucn_category="II",
                country="Ecuador",
                country_code="EC",
                state="Orellana & Pastaza Provinces",
                area_km2=9823.0,
                total_hectares=982300.0,
                coordinates={"lat": -0.9997, "lon": -75.9995},
                forest_cover_percent=91.4,
                canopy_loss_year_ha=312.6,
                active_fires_count=14,
                threat_index=68,
                biome="Amazonian Moist Lowland Rainforest",
                last_analyzed="2026-09-17T22:45:00Z",
            ),
            ProtectedAreaModel(
                id="area-4",
                wdpa_id="WDPA-1982",
                name="Mamirauá Sustainable Development Reserve",
                designation="Ramsar Wetland & Sustainable Reserve",
                protected_area_type="Sustainable Development Reserve (Ramsar)",
                iucn_category="VI",
                country="Brazil",
                country_code="BR",
                state="Amazonas",
                area_km2=11240.0,
                total_hectares=1124000.0,
                coordinates={"lat": -2.2514, "lon": -65.2341},
                forest_cover_percent=86.9,
                canopy_loss_year_ha=215.1,
                active_fires_count=8,
                threat_index=52,
                biome="Várzea Flooded Freshwater Forest",
                last_analyzed="2026-09-16T14:10:00Z",
            ),
            ProtectedAreaModel(
                id="area-5",
                wdpa_id="WDPA-641",
                name="Virunga National Park",
                designation="National Park (In Danger)",
                protected_area_type="National Park & UNESCO World Heritage (In Danger)",
                iucn_category="II",
                country="Democratic Republic of Congo",
                country_code="CD",
                state="North Kivu",
                area_km2=7800.0,
                total_hectares=780000.0,
                coordinates={"lat": -0.0833, "lon": 29.5},
                forest_cover_percent=82.1,
                canopy_loss_year_ha=410.5,
                active_fires_count=19,
                threat_index=84,
                biome="Albertine Rift Montane Forests & Volcanic Slopes",
                last_analyzed="2026-09-18T03:45:00Z",
            ),
        ]
        for a in areas_data:
            self.areas[a.id] = a

        # 2. Seed Statistics & Timelines for each area
        for a in areas_data:
            self.statistics[a.id] = AreaStatisticsModel(
                area_id=a.id,
                area_name=a.name,
                forest_cover_percent=a.forest_cover_percent,
                canopy_loss_year_ha=a.canopy_loss_year_ha,
                water_bodies_ha=round(a.total_hectares * 0.082, 1),
                urban_builtup_ha=round(a.total_hectares * 0.015, 1),
                habitat_change_score=round((100 - a.threat_index) * 0.85, 1),
                active_fires_count=a.active_fires_count,
                threat_index=a.threat_index,
                last_cloud_free_pass=a.last_analyzed,
                land_cover_distribution={
                    "Dense Forest Canopy": a.forest_cover_percent,
                    "Open Woodland": round(a.forest_cover_percent * 0.18, 1),
                    "Grassland / Meadow": round((100 - a.forest_cover_percent) * 0.5, 1),
                    "Water & Wetlands": 8.2,
                    "Settlement & Roads": 1.5,
                },
                sensor_telemetry={
                    "satellite": "Sentinel-2 MSI",
                    "resolution_m": 10,
                    "cloud_cover_percent": 1.4,
                    "sun_elevation_deg": 58.2,
                },
            )

            # Monthly timeline data
            self.timelines[a.id] = [
                AreaTimelineModel(
                    date=f"2026-{m:02d}-01",
                    ndvi=round(0.72 + (0.05 if m in [7, 8, 9] else -0.04), 2),
                    baseline=0.74,
                    water_cover_ha=round(a.total_hectares * 0.08, 1),
                    fire_incidents=max(0, a.active_fires_count - (m % 3)),
                    canopy_loss_ha=round(a.canopy_loss_year_ha / 12 * (1 + (m % 3) * 0.2), 1),
                )
                for m in range(1, 10)
            ]

        # 3. Seed Hotspots
        hotspots_data = [
            HotspotModel(
                id="HS-KANHA-01",
                area_id="area-kanha",
                area_name="Kanha National Park",
                location_detail="North-West Buffer Sector, Mukki Range",
                detected_at="2026-09-17T06:30:00Z",
                area_ha=14.8,
                delta_ndvi=-0.52,
                percentage_change=-44.8,
                change_type="VEGETATION_LOSS",
                severity="CRITICAL",
                confidence_score=0.96,
                coordinates={"lat": 22.348, "lon": 80.625},
                status="NEW",
                sensor="Sentinel-2 MSI (10m)",
                previous_condition="Intact Primary Moist Sal Canopy (Mean NDVI: 0.79), Dense Crown Cover >85%",
                current_condition="High Canopy Disturbance with Fragmented Crown Exposure (Mean NDVI: 0.27)",
                potential_contributing_factors=[
                    "Proximity to unprotected peripheral forest corridor (< 450 m)",
                    "Linear road/haulage track geometry detected on shortwave infrared (B11/B8)",
                    "Gentle slope accessibility (< 6°) allowing vehicular transit",
                    "Recent dry season soil moisture deficit observed across sector",
                ],
                related_alerts=[
                    HotspotRelatedAlert(
                        id="ALT-KANHA-881",
                        title="Critical Canopy Deficit Detected in Mukki Sector",
                        severity="CRITICAL",
                        timestamp="2026-09-17T07:15:00Z",
                    )
                ],
            ),
            HotspotModel(
                id="HS-BANDH-02",
                area_id="area-bandhavgarh",
                area_name="Bandhavgarh National Park",
                location_detail="Tala Core Zone, Eastern Boundary",
                detected_at="2026-09-17T14:45:00Z",
                area_ha=9.7,
                delta_ndvi=-0.45,
                percentage_change=-37.8,
                change_type="URBAN_EXPANSION",
                severity="HIGH",
                confidence_score=0.91,
                coordinates={"lat": 23.718, "lon": 81.015},
                status="NEW",
                sensor="Sentinel-2 MSI (10m)",
                previous_condition="Mixed Deciduous Forest with Bamboo Understory (Mean NDVI: 0.72)",
                current_condition="Cleared Clearing with Linear Built Structures (NDBI: +0.28, NDVI: 0.35)",
                potential_contributing_factors=[
                    "Contiguous extension from existing rural settlement road network",
                    "High NDBI spectral signature indicating compacted soil and impervious materials",
                ],
                related_alerts=[
                    HotspotRelatedAlert(
                        id="ALT-BANDH-402",
                        title="Encroachment Signature Identified near Tala Sector",
                        severity="HIGH",
                        timestamp="2026-09-17T15:20:00Z",
                    )
                ],
            ),
            HotspotModel(
                id="HS-SATP-03",
                area_id="area-satpura",
                area_name="Satpura Tiger Reserve",
                location_detail="Bori Wildlife Sanctuary Zone, Pachmarhi Slopes",
                detected_at="2026-09-16T17:20:00Z",
                area_ha=16.3,
                delta_ndvi=-0.54,
                percentage_change=-46.2,
                change_type="FIRE",
                severity="CRITICAL",
                confidence_score=0.97,
                coordinates={"lat": 22.495, "lon": 78.249},
                status="NEW",
                sensor="VIIRS 375m / S2 MSI",
                previous_condition="Dry Deciduous Teak & Bamboo Canopy (Mean NDVI: 0.68)",
                current_condition="Active Thermal Scar with Carbon Residuals (Normalized Burn Ratio: -0.42)",
                potential_contributing_factors=[
                    "VIIRS active thermal detection (42.6 MW FRP) recorded 6 hours prior to pass",
                    "Elevated fuel load accumulated following prolonged dry spell",
                ],
                related_alerts=[
                    HotspotRelatedAlert(
                        id="ALT-SATP-912",
                        title="Thermal Anomaly (VIIRS 42.6 MW) Confirmed by Sentinel-2 Burn Scar",
                        severity="CRITICAL",
                        timestamp="2026-09-16T17:45:00Z",
                    )
                ],
            ),
            HotspotModel(
                id="HS-KAZI-04",
                area_id="area-2",
                area_name="Kaziranga National Park",
                location_detail="Bagori Range, Brahmaputra Floodplain",
                detected_at="2026-09-17T11:05:00Z",
                area_ha=6.8,
                delta_ndvi=-0.39,
                percentage_change=-33.4,
                change_type="WATER_LOSS",
                severity="HIGH",
                confidence_score=0.92,
                coordinates={"lat": 26.589, "lon": 93.182},
                status="NEW",
                sensor="Sentinel-2 MSI (10m)",
                previous_condition="Perennial Wetland Channel & Oxbow Beel (Mean NDWI: +0.52)",
                current_condition="Desiccated Silt Splay and Silt Deposition (Mean NDWI: -0.18)",
                potential_contributing_factors=[
                    "Post-monsoon river course silt deposition along main river braiding channel",
                    "Reduced upstream tributary discharge following dry seasonal cycle",
                ],
                related_alerts=[],
            ),
            HotspotModel(
                id="HS-SEREN-05",
                area_id="area-1",
                area_name="Serengeti National Park",
                location_detail="Northern Sector, Mara River Basin Corridor",
                detected_at="2026-09-15T09:15:00Z",
                area_ha=5.1,
                delta_ndvi=-0.31,
                percentage_change=-24.0,
                change_type="OTHER",
                severity="MEDIUM",
                confidence_score=0.84,
                coordinates={"lat": -2.312, "lon": 34.814},
                status="VERIFIED",
                sensor="Sentinel-2 MSI (10m)",
                previous_condition="Acacia Savanna Woodland (Mean NDVI: 0.65)",
                current_condition="Thinned Crown Cover with Soil Exposure (Mean NDVI: 0.44)",
                potential_contributing_factors=[
                    "High ungulate herd concentration recorded along migration staging area",
                    "Seasonal dry spell accelerating foliage shedding",
                ],
                related_alerts=[],
            ),
            HotspotModel(
                id="HS-VIRUN-08",
                area_id="area-5",
                area_name="Virunga National Park",
                location_detail="Southern Sector, Mikeno Gorilla Sector",
                detected_at="2026-09-17T08:24:00Z",
                area_ha=14.8,
                delta_ndvi=-0.52,
                percentage_change=-44.8,
                change_type="VEGETATION_LOSS",
                severity="CRITICAL",
                confidence_score=0.95,
                coordinates={"lat": -0.082, "lon": 29.491},
                status="NEW",
                sensor="Sentinel-2 MSI (10m)",
                previous_condition="Montane Tropical Rainforest (Mean NDVI: 0.82)",
                current_condition="Extensive Canopy Clearance & Charcoal Kiln Footprints (Mean NDVI: 0.31)",
                potential_contributing_factors=[
                    "Proximity to vulnerable boundary settlement (< 800 m)",
                    "High thermal cluster correlation indicative of illicit charcoal production",
                ],
                related_alerts=[],
            ),
        ]
        for h in hotspots_data:
            self.hotspots[h.id] = h

        # 4. Seed Alerts
        alerts_data = [
            AlertModel(
                id="ALT-KANHA-881",
                title="Critical Canopy Deficit Detected in Mukki Sector",
                message="Sentinel-2 Level-2A pass recorded a 14.8 ha acute canopy loss patch with -0.52 ΔNDVI.",
                severity="CRITICAL",
                status="UNREAD",
                triggered_at="2026-09-17T07:15:00Z",
                area_id="area-kanha",
                area_name="Kanha National Park",
                hotspot_id="HS-KANHA-01",
            ),
            AlertModel(
                id="ALT-SATP-912",
                title="Thermal Anomaly (VIIRS 42.6 MW) Confirmed by Sentinel-2 Burn Scar",
                message="VIIRS thermal hotspot verified by 16.3 ha burn scar polygon on Pachmarhi slopes.",
                severity="CRITICAL",
                status="UNREAD",
                triggered_at="2026-09-16T17:45:00Z",
                area_id="area-satpura",
                area_name="Satpura Tiger Reserve",
                hotspot_id="HS-SATP-03",
            ),
            AlertModel(
                id="ALT-BANDH-402",
                title="Encroachment Signature Identified near Tala Sector",
                message="SWIR-derived NDBI spike indicates 9.7 ha soil compaction and linear road construction.",
                severity="HIGH",
                status="UNREAD",
                triggered_at="2026-09-17T15:20:00Z",
                area_id="area-bandhavgarh",
                area_name="Bandhavgarh National Park",
                hotspot_id="HS-BANDH-02",
            ),
            AlertModel(
                id="ALT-KAZI-304",
                title="Oxbow Wetland Desiccation in Bagori Range",
                message="Surface water reduction of 6.8 ha detected following Brahmaputra silt deposition.",
                severity="HIGH",
                status="ACKNOWLEDGED",
                triggered_at="2026-09-17T12:00:00Z",
                area_id="area-2",
                area_name="Kaziranga National Park",
                hotspot_id="HS-KAZI-04",
            ),
            AlertModel(
                id="ALT-VIRUN-780",
                title="Critical Montane Forest Clearance in Mikeno Sector",
                message="High-probability charcoal production cluster affecting 14.8 ha in mountain gorilla habitat.",
                severity="CRITICAL",
                status="UNREAD",
                triggered_at="2026-09-17T09:00:00Z",
                area_id="area-5",
                area_name="Virunga National Park",
                hotspot_id="HS-VIRUN-08",
            ),
        ]
        for al in alerts_data:
            self.alerts[al.id] = al

        # 5. Seed Reports
        reports_data = [
            ReportModel(
                id="REP-2026-09-01",
                title="Monthly Habitat Integrity Audit - September 2026",
                format="GEOPDF",
                date_range="2026-08-15 to 2026-09-15",
                area_id="area-kanha",
                area_name="Kanha National Park",
                file_size_mb=14.2,
                status="READY",
                generated_at="2026-09-17T18:00:00Z",
                download_url="/api/reports/REP-2026-09-01/download",
            ),
            ReportModel(
                id="REP-2026-09-02",
                title="Bi-Temporal Change Vector Dossier - Tala Encroachment",
                format="GEOPACKAGE",
                date_range="2024-09-01 to 2026-09-01",
                area_id="area-bandhavgarh",
                area_name="Bandhavgarh National Park",
                file_size_mb=28.7,
                status="READY",
                generated_at="2026-09-17T16:30:00Z",
                download_url="/api/reports/REP-2026-09-02/download",
            ),
            ReportModel(
                id="REP-2026-09-03",
                title="Quarterly Hotspot Incidents CSV Export",
                format="CSV",
                date_range="2026-06-01 to 2026-09-15",
                area_id="area-satpura",
                area_name="Satpura Tiger Reserve",
                file_size_mb=3.8,
                status="READY",
                generated_at="2026-09-16T12:00:00Z",
                download_url="/api/reports/REP-2026-09-03/download",
            ),
        ]
        for r in reports_data:
            self.reports[r.id] = r


db = InMemoryDatabase()
